#!/bin/sh

###############################################################
# Keyboard
#################

sysresources=/etc/X11/xinit/.Xresources
[[ -f "$sysresources" ]] && xrdb -merge "$sysresources"
userresources="$HOME/.Xresources"
[[ -f "$userresources" ]] && xrdb -merge "$userresources"

sysmodmap=/etc/X11/xinit/.Xmodmap
[[ -f "$sysmodmap" ]] && xmodmap "$sysmodmap"

# add layouts, switch its with LeftCtrl+LeftWin
setxkbmap -layout us,ru -option grp:lctrl_lwin_toggle
# change CapsLock → Ctrl
setxkbmap -option ctrl:nocaps
# add Compose key
setxkbmap -option compose:menu

# make short-pressed Ctrl behave like Escape:
xcape -e 'Control_L=Escape'

# Num Lock
if type "numlockx" &> /dev/null; then
  numlockx on
fi

###############################################################
# Autostart
#################

# Global
sysxinit=/etc/X11/xinit/xinitrc.d
if [ -d "$sysxinit" ] ; then
 for f in "$sysxinit"/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Local
eval `ssh-agent -a $SSH_AUTH_SOCK`

###############################################################
# Windows management
#################
exec i3
