version: '3'

services:

  postgres:
    image: postgres:alpine
    container_name: project-postgres
    environment:
      POSTGRES_PASSWORD: project-password
      POSTGRES_USER: project
    volumes:
      - ./tmp:/tmp-host

  redis:
    image: redis:alpine
    container_name: project-redis

  project:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      PROJECT: project
      PYTHONPATH: '/itcase/itcase-plugin'
    ports:
      - '127.0.0.1:8000:8000'
      - '127.0.0.1:19360:19360'
    stdin_open: true
    tty: true
    volumes:
      - ./src:/code
      - ./tmp:/tmp-host

      - ../itcase-dev:/itcase

      - ~/.config/sublime-text-3/Packages/Anaconda:/opt/anaconda

