version: '3'

networks:
  default:
    external: true
    name: docker1

services:

  django:
    image: project
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      #elasticsearch:
      #  condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      PROJECT: project
      PYTHONPATH: '/itcase/itcase-plugin:/itcase/itcase-plugin'
    ports:
      - '127.0.0.1:8000:8000'
      - '127.0.0.1:19360:19360'
    stdin_open: true
    tty: true
    volumes:
      - ./src:/code
      - ./tmp:/tmp-host

      - ../itcase-dev:/itcase

 #elasticsearch:
 #  image: elasticsearch:6.8.12
 #  container_name: project-elasticsearch
 #  environment:
 #    discovery.type: single-node
 #    ES_JAVA_OPTS: "-Xmx128mb -Xms128mb"
 #  healthcheck:
 #    test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
 #    interval: 10s
 #    timeout: 5s
 #    retries: 5
 #  ports:
 #    - '127.0.0.1:9200:9200'

  postgres:
    image: postgres:alpine
    container_name: project-postgres
    environment:
      POSTGRES_PASSWORD: project-password
      POSTGRES_USER: project
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U project"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./tmp:/tmp-host

  redis:
    image: redis:alpine
    container_name: project-redis
