#!/bin/sh

###############################################################
# Keyboard
#################

sysresources=/etc/X11/xinit/.Xresources
[[ -f "$sysresources" ]] && xrdb -merge "$sysresources"
userresources="$HOME/.Xresources"
[[ -f "$userresources" ]] && xrdb -merge "$userresources"

sysmodmap=/etc/X11/xinit/.Xmodmap
[[ -f "$sysmodmap" ]] && xmodmap "$sysmodmap"
usermodmap="$HOME/.Xmodmap"
[[ -f "$usermodmap" ]] && xmodmap "$usermodmap"

###############################################################
# Autostart
#################

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Dropbox
exec ~/.dropbox-dist/dropboxd &

# Screenlock
exec xautolock -time 1 -locker i3lock &

###############################################################
# Windows management
#################
exec i3

