#!/bin/sh

###############################################################
# Keyboard
#################

sysresources=/etc/X11/xinit/.Xresources
[[ -f "$sysresources" ]] && xrdb -merge "$sysresources"
userresources="$HOME/.Xresources"
[[ -f "$userresources" ]] && xrdb -merge "$userresources"

sysmodmap=/etc/X11/xinit/.Xmodmap
[[ -f "$sysmodmap" ]] && xmodmap "$sysmodmap"
usermodmap="$HOME/.Xmodmap"
[[ -f "$usermodmap" ]] && xmodmap "$usermodmap"

###############################################################
# Autostart
#################

# start some programs
scripts="/etc/X11/xinit/xinitrc.d"
if [ -d "$scripts" ] ; then
 for f in "$scripts/?*.sh" ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Dropbox
exec ~/.dropbox-dist/dropboxd &

# Screenlock
exec xautolock -time 3 -locker i3lock &

# Num Lock
if type "numlockx" &> /dev/null; then
  numlockx on
fi

###############################################################
# Windows management
#################
exec i3

