#!/bin/sh
#
# Show and control sound volume
#
# If you not see $label below use other font :)

# Left click
if [ "$BLOCK_BUTTON" = "1" ]; then
  pactl set-sink-mute @DEFAULT_SINK@ yes
# Middle click
elif [ "$BLOCK_BUTTON" = "2" ]; then
  i3-msg -q exec pavucontrol
# Right click
elif [ "$BLOCK_BUTTON" = "3" ]; then
  pactl set-sink-mute @DEFAULT_SINK@ no
fi

background="#002B36"
code=0
color="#93A1A1"
label="蓼"

data=$(pacmd list-sinks | awk '/^\s+\* index:/, /^\s+active port:/')
mute=$(echo "$data" | awk '/^\s+muted:/ {print $2 == "yes"}')
volume=$(echo "$data" | awk '/^\s+volume:/ {print $5}')

if [ "$mute" -eq "1" ]; then
  color="#B58900"
  label="遼"
fi

text_full="$label $volume"
text_short="$text_full"

echo "$text_full"
echo "$text_short"
echo "$color"
echo "$background"

exit "$code"
