#!/usr/bin/env bash
#
# Based on https://github.com/Anachron/i3blocks

PREV_TOTAL=0
PREV_IDLE=0

crit_color="#DC322F"
crit_threshold=90    # %

warn_color="#B58900"
warn_threshold=80    # %

cpuFile="/tmp/.cpu"

if [[ -f "${cpuFile}" ]]; then
  fileCont=$(cat "${cpuFile}")
  PREV_TOTAL=$(echo "${fileCont}" | head -n 1)
  PREV_IDLE=$(echo "${fileCont}" | tail -n 1)
fi

CPU=(`cat /proc/stat | grep '^cpu '`) # Get the total CPU statistics.
unset CPU[0]                          # Discard the "cpu" prefix.
IDLE=${CPU[4]}                        # Get the idle CPU time.

# Calculate the total CPU time.
TOTAL=0

for VALUE in "${CPU[@]:0:4}"; do
  let "TOTAL=$TOTAL+$VALUE"
done

if [[ "${PREV_TOTAL}" != "" ]] && [[ "${PREV_IDLE}" != "" ]]; then
  # Calculate the CPU usage since we last checked.
  let "DIFF_IDLE=$IDLE-$PREV_IDLE"
  let "DIFF_TOTAL=$TOTAL-$PREV_TOTAL"
  let "DIFF_USAGE=(1000*($DIFF_TOTAL-$DIFF_IDLE)/$DIFF_TOTAL+5)/10"
fi

label="${BLOCK_LABEL:-}"
echo "$label ${DIFF_USAGE:-?}%"
echo "$label ${DIFF_USAGE:-?}%"

# Remember the total and idle CPU times for the next check.
echo "${TOTAL}" > "${cpuFile}"
echo "${IDLE}" >> "${cpuFile}"

if [[ "${DIFF_USAGE}" -ge "${crit_threshold}" ]] ; then
  echo "${crit_color}"
  exit 33
fi

[[ "${DIFF_USAGE}" -ge "${warn_threshold}" ]] &&  echo "${warn_color}"

exit 0
