#!/usr/bin/env zsh
#
# Show percentage of CPU usage in Solarized Dark colorscheme
#
# Requirements:
#  `sysstat`:
#    sudo pacman -S sysstat
#  `netcat`:
#    sudo pacman -S gnu-netcat

crit_color="#DC322F"
crit_threshold=80    # %

warn_color="#B58900"
warn_threshold=50    # %

usage="$(mpstat | awk '$3 ~ /CPU/ { for(i=1;i<=NF;i++) { if ($i ~ /%idle/) field=i } } $3 ~ /all/ { print 100 - $field }')"

printf "%.2f%%\n" "$usage"
printf "%.2f%%\n" "$usage"

if [[ "$usage" -ge "$crit_threshold" ]] ; then
  echo "$crit_color"
  exit 33
fi

[[ "$usage" -ge "$warn_threshold" ]] &&  echo "$warn_color"

exit 0
