#!/bin/sh
#
# Show temperature of CPU in Solarized Dark colorscheme
#
# if you not see $label below use other font :)

################################################################
# Click
################################################################

[ -n "$BLOCK_BUTTON" ] && pkill -f conky
# Left click
if [ "$BLOCK_BUTTON" = "1" ]; then
  i3-msg -q exec conky
# Middle click
#elif [ "$BLOCK_BUTTON" = "2" ]; then
# Right click
#elif [ "$BLOCK_BUTTON" = "3" ]; then
fi

################################################################
# Output
################################################################

background="#002B36"
code=0
color="#93A1A1"
label=""

device="/sys/class/hwmon/hwmon0/temp2_"
data=$(cat $device"input")

warn_threshold=$(cat $device"max")
if [ "$data" -ge "$warn_threshold" ]; then
  color="#B58900"
  label=""
fi

crit_threshold=$(cat $device"crit")
if [ "$data" -ge "$crit_threshold" ]; then
  background="#CB4B16"
  code=33
  color="#FDF6E3"
  label=""
fi

text_full="$label $(echo $data | awk '{print substr($1, 1, length($1)-3)a}')°C"
text_short="$text_full"

echo "$text_full"
echo "$text_short"
echo "$color"
echo "$background"

exit "$code"
