#!/usr/bin/env bash
#
# Show free space in Solarized Dark colorscheme
#
# If you not see $label below use other font :)

background="#002B36"
code=0
color="#93A1A1"
label=""

data="$(df -hlP ${BLOCK_INSTANCE:-$HOME})"
size="$(echo "$data" | awk '/\/.*/ { print $2 }')"
avail="$(echo "$data" | awk '/\/.*/ { print $4 }')"
use="$(echo "$data" | awk '/\/.*/ { gsub(/%$/, "", $5); print $5 }')"

text_full="$label $avail ($size)"
text_short="$text_full"

warn_threshold=75  # %
[[ "$use" -ge "$warn_threshold" ]] && color="#B58900"

crit_threshold=90  # %
if [[ "$use" -ge "$crit_threshold" ]] ; then
  background="#CB4B16"
  code=33
  color="#FDF6E3"
fi

echo "$text_full"
echo "$text_short"
echo "$color"
echo "$background"

exit "$code"
