#!/bin/sh
#
# Show temperature of HDD in Solarized Dark colorscheme
#
# Requirements:
#   sudo pacman -S hddtemp gnu-netcat
#   systemctl enable hddtemp.service
#   systemctl start hddtemp.service
#
# If you not see $label below use other font :)

background="#002B36"
code=0
color="#93A1A1"
label=""

data="$(nc localhost 7634 | awk -F'|' '{print $4}')"

warn_threshold=50  # °C
if [ "$data" -ge "$warn_threshold" ]; then
  color="#B58900"
  label=""
fi

crit_threshold=60  # °C
if [ "$data" -ge "$crit_threshold" ]; then
  background="#CB4B16"
  code=33
  color="#FDF6E3"
  label=""
fi

text_full="$label $data°C"
text_short="$text_full"

echo "$text_full"
echo "$text_short"
echo "$color"
echo "$background"

exit "$code"
