#!/usr/bin/env sh
# Based on https://github.com/vivien/i3blocks-contrib

stat="$(cut -d ' ' -f1 /proc/loadavg)"

label="${BLOCK_LABEL:-}"
echo "$label $stat"
echo "$label $stat"

# color if load is too high
awk -v cpus="$(nproc)" -v cpuload="$stat" '
    BEGIN {
        if (cpus <= cpuload) {
            print "#DC322F";
            exit 33;
        }
    }
'
