#!/bin/sh
#
# Show load average
#
# If you not see $label below use other font :)

background="#002B36"
code=0
color="#93A1A1"
data="$(cut -d ' ' -f1 /proc/loadavg)"
label=""
text_full="$label $data"
text_short="$text_full"

warn_threshold="$(nproc)"
[ $(echo "$data>=$warn_threshold" | bc) -ne "0" ] && color="#B58900"

crit_threshold=$(echo "$warn_threshold*2" | bc)
if [ $(echo "$data>=$crit_threshold" | bc) -ne 0 ]; then
  background="#CB4B16"
  code=33
  color="#FDF6E3"
fi

echo "$text_full"
echo "$text_short"
echo "$color"
echo "$background"

exit "$code"
