#!/bin/bash

device="${BLOCK_INSTANCE:-wlan0}"
data="$(cat /sys/class/net/$device/operstate)"

URGENT_VALUE=20

if [[ "$data" == "up" ]]; then
  let text="on"
  let code=0

  if [[ -d "/sys/class/net/$device/wireless" ]]; then
    quality=$(grep $device /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    text="$quality%"
    if [[ "$quality" -le "$URGENT_VALUE" ]]; then
      code=33
    fi
  fi

  let label="${BLOCK_LABEL:-}"
  echo "$label $text"
  echo "$label $text"
  echo ""
  exit "$code"
fi
