#!/usr/bin/env bash
#
# Show IP for ethernet / SSID for wifi connection
#
# Requirements (for wifi only):  sudo pacman -S iw
#
# If you not see $label below use other font :)

background="#002B36"
code=0
color="#93A1A1"
device="$BLOCK_INSTANCE"
label=""

if [[ -d "/sys/class/net/$device/wireless" ]]; then
  data=$(grep $device /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
  text="$(iwgetid -r) ($data%)"

  warn_threshold=50
  [[ "$data" -le "$warn_threshold" ]] && color="#B58900"

  crit_threshold=20
  if [[ "$data" -le "$crit_threshold" ]]; then
    background="#CB4B16"
    code=33
    color="#FDF6E3"
  fi
else
  data="$(ip addr show $device 2> /dev/null)" || exit
  label=""
  text="$(echo $data | grep -oP '(?<=inet\s)\d+(\.\d+){3}')"

  state="$(echo $data | grep -oP '(?<=state\s)\w+')"
  [[ "$state" != "UP" ]] && color="#B58900"
  if [[ "$state" == "DOWN" ]]; then
    background="#CB4B16"
    code=33
    color="#FDF6E3"
  fi
fi

text_full="${BLOCK_LABEL:-$label} $text"
text_short="$text_full"

echo "$text_full"
echo "$text_short"
echo "$color"
echo "$background"

exit "$code"
