#!/usr/bin/env bash
#
# Show count of availabel updates
#
# If you not see $label below use other font :)

background="#002B36"
code=0
color="#93A1A1"
label=""

data=$(pacman -Qu | wc -l)
[[ "$data" == 0 ]] && exit

text_full="$label $data"
text_short="$text_full"

warn_threshold=75
#[[ $(echo "$data>=$warn_threshold" | bc) -ne 0 ]] && color="#B58900"
[[ "$data" -ge "$warn_threshold" ]] && color="#B58900"

crit_threshold=100
if [[ "$data" -ge "$crit_threshold" ]]; then
  background="#CB4B16"
  code=33
  color="#FDF6E3"
fi

echo "$text_full"
echo "$text_short"
echo "$color"
echo "$background"

exit "$code"
