#!/usr/bin/env bash
#
# Show count of available new packages Solarized Dark colorscheme

crit_color="#DC322F"
crit_threshold=75

warn_color="#B58900"
warn_threshold=50

count="$(pacman -Qu | wc -l)"

[[ "${count}" == 0 ]] && exit

echo "${count}"
echo "${count}"

if [[ "${count}" -ge "${crit_threshold}" ]] ; then
  echo "${crit_color}"
  exit 33
fi

[[ "${count}" -ge "${warn_threshold}" ]] && echo "${warn_color}"

exit 0
