#!/usr/bin/env zsh
#
# Show temperature of CPU in Solarized Dark colorscheme
#
# Requirements:
#  `lm-sensors`:
#    sudo pacman -S lm_sensors
#  Font with support of icons:
#    if you not see $LABEL below use other font :)

crit_color="#DC322F"
crit_label=""
crit_threshold=90    # °C

label=""

warn_color="#B58900"
warn_label=""
warn_threshold=70    # °C

temperature="$(sensors | awk '/temp1/ { gsub(/^\+|\.[[:digit:]]+|[^0-9]+$/, "", $2); print $2 }')"

if [[ "$temperature" -ge "$warn_threshold" ]] ; then
  color="$warn_color"
  label="$warn_label"
fi

if [[ "$temperature" -ge "$crit_threshold" ]] ; then
  crit=true
  color="$crit_color"
  label="$crit_label"
fi

echo "$label $temperature°C"
echo "$label $temperature°C"

[[ -n $color ]] && echo "$color"
[[ "$crit" = true ]] && exit 33

exit 0
