#!/usr/bin/env bash
#
# Show temperature of CPU in Solarized Dark colorscheme
#
# Requirements: sudo pacman -S lm_sensors
#
# if you not see $label below use other font :)

background="#002B36"
code=0
color="#93A1A1"
label=""

data=$(sensors | awk '/Core 0/ { gsub(/^\+|\.[[:digit:]]+|[^0-9]+$/, "", $3); print $3 }')

warn_threshold=70  # °C
if [[ "$data" -ge "$warn_threshold" ]]; then
  color="#B58900"
  label=""
fi

crit_threshold=90  # °C
if [[ "$data" -ge "$crit_threshold" ]]; then
  background="#CB4B16"
  code=33
  color="#FDF6E3"
  label=""
fi

text_full="$label $data°C"
text_short="$text_full"

echo "$text_full"
echo "$text_short"
echo "$color"
echo "$background"

exit "$code"
